### ISSUE TITLE
Unable to share address book by delegation

### ISSUE THREAD

**Issue by hantt12** [OpenPaaS-Suite/esn-frontend-contacts#32]
Steps to reproduce:

1. Go to settings of a certain address book
2. Select Delegation tab

Expected result:
User should be able to input user to share with and select permissions

Actual result:
There is no field to input user to share with

![20200821](https://user-images.githubusercontent.com/53081477/90849057-97d3dd80-e398-11ea-9bfa-14c846ac6216.png)

**Comment by asmaNode** [comment]
depends on #33

**Comment by huy-ta** [comment]
@asmaNode Please write a simple DoD like [this one](https://github.com/OpenPaaS-Suite/esn-frontend-inbox/issues/74#issuecomment-678178312) and then @ one of the members of the QA team (preferrably the author of the issue) so that he/she can receive a mail notification.

**Comment by tlle14** [comment]
Hi @asmaNode 

Retest failed! 
We have a text field but unable to add a delegated user:

**Actual Result:**
- No suggestion when input user email
- Error log display and nothing happens when clicking "Add" button

![image](https://user-images.githubusercontent.com/69950655/92065401-de2e3100-edc9-11ea-848a-14879e2bf593.png)

![delegation](https://user-images.githubusercontent.com/69950655/92065378-d3739c00-edc9-11ea-9ea2-08d31a4c9c96.gif)

**Expected Result**

User should be able to delegate a contact

**Comment by tuanlc** [comment]
@tlle14 can you re-test? For me, it works on dev platform. Maybe the code does not up to date at the moment you tested.

**Comment by tlle14** [comment]
Hi @tuanlc @asmaNode 

Retest pass!
![image](https://user-images.githubusercontent.com/69950655/92347798-53b43d00-f0fb-11ea-8e59-f736bf4b46c4.png)

Thank you
